<?php

return [
  [
    "title" => "插件管理",
    "path" => "Plugins",
    "method" => "GET",
    "type" => "10",
    "icon" => "AppstoreOutlined",
    "params" => "",
    "is_show" => 20,
    'state' => '20',
    "sort" => 20,
    "pid" => "",
    'children' => [
      [
        'title' => '开发辅助',
        'plugin' => 'xbDeveloper',
        'path' => 'admin/Index/index',
        'type' => '20',
        'icon' => '',
        'params' => '',
        'is_show' => '20',
        'is_system' => '10',
        'is_saas' => '10',
        'sort' => 100,
        'children' => [
          [
            'title' => '创建插件',
            'plugin' => 'xbDeveloper',
            'path' => 'admin/Index/create',
            'type' => '30',
            'icon' => '',
            'params' => '',
            'is_show' => '10',
            'is_system' => '10',
            'is_saas' => '10',
            'sort' => 0,
            'children' => [],
          ],
          [
            'title' => '安装插件',
            'plugin' => 'xbDeveloper',
            'path' => 'admin/Index/install',
            'type' => '30',
            'icon' => '',
            'params' => '',
            'is_show' => '10',
            'is_system' => '10',
            'is_saas' => '10',
            'sort' => 0,
            'children' => [],
          ],
          [
            'title' => '更新插件',
            'plugin' => 'xbDeveloper',
            'path' => 'admin/Index/update',
            'type' => '30',
            'icon' => '',
            'params' => '',
            'is_show' => '10',
            'is_system' => '10',
            'is_saas' => '10',
            'sort' => 0,
            'children' => [],
          ],
          [
            'title' => '卸载插件',
            'plugin' => 'xbDeveloper',
            'path' => 'admin/Index/uninstall',
            'type' => '30',
            'icon' => '',
            'params' => '',
            'is_show' => '10',
            'is_system' => '10',
            'is_saas' => '10',
            'sort' => 0,
            'children' => [],
          ],
          [
            'title' => '导出插件数据',
            'plugin' => 'xbDeveloper',
            'path' => 'admin/Index/export',
            'type' => '30',
            'icon' => '',
            'params' => '',
            'is_show' => '10',
            'is_system' => '10',
            'is_saas' => '10',
            'sort' => 0,
            'children' => [],
          ],
          [
            'title' => '更新插件菜单',
            'plugin' => 'xbDeveloper',
            'path' => 'admin/Index/menus',
            'type' => '30',
            'icon' => '',
            'params' => '',
            'is_show' => '10',
            'is_system' => '10',
            'is_saas' => '10',
            'sort' => 0,
            'children' => [],
          ],
          [
            'title' => '执行插件SQL',
            'plugin' => 'xbDeveloper',
            'path' => 'admin/Index/sql',
            'type' => '30',
            'icon' => '',
            'params' => '',
            'is_show' => '10',
            'is_system' => '10',
            'is_saas' => '10',
            'sort' => 0,
            'children' => [],
          ],
          [
            'title' => '克隆插件仓库',
            'plugin' => 'xbDeveloper',
            'path' => 'admin/Index/clone',
            'type' => '30',
            'icon' => '',
            'params' => '',
            'is_show' => '10',
            'is_system' => '10',
            'is_saas' => '10',
            'sort' => 0,
            'children' => [],
          ],
        ],
      ],
    ],
  ],
];