<?php

return [
    [
        'title' => '系统配置',
        'path' => 'Config',
        'method' => 'GET',
        'type' => '10',
        'icon' => 'Setting',
        'params' => '',
        'is_show' => '20',
        'is_system' => '10',
        'state' => '20',
        'sort' => 9999,
        'children' => [
            [
                'title' => '定时任务',
                'path' => 'admin/Index/index',
                'method' => 'GET',
                'type' => '20',
                'icon' => 'ClockCircleOutlined',
                'params' => '',
                'is_show' => '20',
                'is_system' => '10',
                'state' => '20',
                'sort' => 5,
                'children' => [
                    [
                        'title' => '添加定时任务',
                        'path' => 'admin/Index/add',
                        'method' => ['GET', 'POST'],
                        'type' => '30',
                        'icon' => '',
                        'params' => '',
                        'is_show' => '10',
                        'is_system' => '10',
                        'state' => '20',
                        'sort' => 1,
                        'children' => [],
                    ],
                    [
                        'title' => '修改定时任务',
                        'path' => 'admin/Index/edit',
                        'method' => ['GET', 'PUT'],
                        'type' => '30',
                        'icon' => '',
                        'params' => '',
                        'is_show' => '10',
                        'is_system' => '10',
                        'state' => '20',
                        'sort' => 2,
                        'children' => [],
                    ],
                    [
                        'title' => '删除定时任务',
                        'path' => 'admin/Index/del',
                        'method' => ['GET', 'DELETE'],
                        'type' => '30',
                        'icon' => '',
                        'params' => '',
                        'is_show' => '10',
                        'is_system' => '10',
                        'state' => '20',
                        'sort' => 3,
                        'children' => [],
                    ],
                    [
                        'title' => '导出定时任务',
                        'path' => 'admin/Index/export',
                        'method' => 'GET',
                        'type' => '30',
                        'icon' => '',
                        'params' => '',
                        'is_show' => '10',
                        'is_system' => '10',
                        'state' => '20',
                        'sort' => 4,
                        'children' => [],
                    ],
                ],
            ],
        ],
    ],
];