<?php

return [
    [
        "title" => "工作台",
        "path" => "workbench",
        "method" => "GET",
        "type" => "20",
        "icon" => "DashboardOutlined",
        "params" => [
            'url' => 'admin/Index/workbench'
        ],
        "is_show" => '20',
        'state' => '20',
        "sort" => 1,
        "pid" => "",
        "children" => [
            [
                "title" => "获取应用信息",
                "path" => "admin/Index/site",
                "method" => "GET",
                "type" => "30",
                "icon" => "",
                "params" => "",
                "is_show" => 10,
                "is_system" => 20,
                'state' => '20',
            ],
            [
                "title" => "系统登录",
                "path" => "admin/Publics/login",
                "method" => "POST",
                "type" => "30",
                "icon" => "",
                "params" => "",
                "is_show" => 10,
                "is_system" => 20,
                'state' => '20',
            ],
            [
                "title" => "退出登录",
                "path" => "admin/Publics/logout",
                "method" => "POST",
                "type" => "30",
                "icon" => "",
                "params" => "",
                "is_show" => 10,
                "is_system" => 20,
                'state' => '20',
            ],
            [
                "title" => "获取用户信息",
                "path" => "admin/Publics/user",
                "method" => "GET",
                "type" => "30",
                "icon" => "",
                "params" => "",
                "is_show" => 10,
                "is_system" => 20,
                'state' => '20',
            ],
            [
                "title" => "个人资料",
                "path" => "admin/Admin/profile",
                "method" => "GET",
                "type" => "30",
                "icon" => "",
                "params" => "",
                "is_show" => 10,
                "is_system" => '20',
                'state' => '20',
                "children" => [],
            ],
        ],
    ],
    [
        "title" => "插件管理",
        "path" => "Plugins",
        "method" => "GET",
        "type" => "10",
        "icon" => "AppstoreOutlined",
        "params" => "",
        "is_show" => 20,
        'state' => '20',
        "sort" => 20,
        "pid" => "",
        "children" => [
            [
                "title" => "本地插件",
                "path" => "admin/Plugins/index",
                "type" => "20",
                "icon" => "",
                "params" => '',
                "is_show" => 20,
                'state' => '20',
                'sort' => 30,
                "children" => [],
            ],
        ],
    ],
    [
        "title" => "权限管理",
        "path" => "Auth",
        "method" => "GET",
        "type" => "10",
        "icon" => "TeamOutlined",
        "params" => "",
        "is_show" => 20,
        "is_system" => 20,
        'state' => '20',
        "sort" => 8888,
        "pid" => "",
        "children" => [
            [
                "title" => "账号管理",
                "path" => "admin/Admin/index",
                "method" => "GET",
                "type" => "20",
                "icon" => "",
                "params" => "",
                "is_show" => 20,
                "is_system" => 20,
                'state' => '20',
                "children" => [
                    [
                        "title" => "账号管理-添加",
                        "path" => "admin/Admin/add",
                        "method" => "GET",
                        "type" => "30",
                        "icon" => "",
                        "params" => "",
                        "is_show" => 10,
                        "is_system" => 20,
                        'state' => '20',
                        "children" => [],
                    ],
                    [
                        "title" => "账号管理-修改",
                        "path" => "admin/Admin/edit",
                        "method" => "GET",
                        "type" => "30",
                        "icon" => "",
                        "params" => "",
                        "is_show" => 10,
                        "is_system" => 20,
                        'state' => '20',
                        "children" => [],
                    ],
                    [
                        "title" => "账号管理-删除",
                        "path" => "admin/Admin/del",
                        "method" => "GET",
                        "type" => "30",
                        "icon" => "",
                        "params" => "",
                        "is_show" => 10,
                        "is_system" => 20,
                        'state' => '20',
                        "children" => [],
                    ],
                    [
                        "title" => "账号管理-编辑列",
                        "path" => "admin/Admin/rowEdit",
                        "method" => "GET",
                        "type" => "30",
                        "icon" => "",
                        "params" => "",
                        "is_show" => 10,
                        "is_system" => 20,
                        'state' => '20',
                        "children" => [],
                    ],
                ],
            ],
            [
                "title" => "角色管理",
                "path" => "admin/AdminRole/index",
                "method" => "GET",
                "type" => "20",
                "icon" => "",
                "params" => "",
                "is_show" => 20,
                "is_system" => 20,
                'state' => '20',
                "children" => [
                    [
                        "title" => "角色管理-添加",
                        "path" => "admin/AdminRole/add",
                        "method" => "GET",
                        "type" => "30",
                        "icon" => "",
                        "params" => "",
                        "is_show" => 10,
                        "is_system" => 20,
                        'state' => '20',
                        "children" => [],
                    ],
                    [
                        "title" => "角色管理-修改",
                        "path" => "admin/AdminRole/edit",
                        "method" => "GET",
                        "type" => "30",
                        "icon" => "",
                        "params" => "",
                        "is_show" => 10,
                        "is_system" => 20,
                        'state' => '20',
                        "children" => [],
                    ],
                    [
                        "title" => "角色管理-删除",
                        "path" => "admin/AdminRole/del",
                        "method" => "GET",
                        "type" => "30",
                        "icon" => "",
                        "params" => "",
                        "is_show" => 10,
                        "is_system" => 20,
                        'state' => '20',
                        "children" => [],
                    ],
                    [
                        "title" => "角色管理-授权",
                        "path" => "admin/AdminRole/auth",
                        "method" => "GET,PUT",
                        "type" => "30",
                        "icon" => "",
                        "params" => "",
                        "is_show" => 10,
                        "is_system" => 20,
                        'state' => '20',
                        "children" => [],
                    ],
                ],
            ],
            [
                "title" => "权限菜单",
                "path" => "admin/AdminRule/index",
                "method" => "GET",
                "type" => "20",
                "icon" => "",
                "params" => "",
                "is_show" => 20,
                "is_system" => 20,
                'state' => '20',
                "children" => [
                    [
                        "title" => "权限菜单-添加",
                        "path" => "admin/AdminRule/add",
                        "method" => "GET",
                        "type" => "30",
                        "icon" => "",
                        "params" => "",
                        "is_show" => 10,
                        "is_system" => 20,
                        'state' => '20',
                        "children" => [],
                    ],
                    [
                        "title" => "权限菜单-修改",
                        "path" => "admin/AdminRule/edit",
                        "method" => "GET",
                        "type" => "30",
                        "icon" => "",
                        "params" => "",
                        "is_show" => 10,
                        "is_system" => 20,
                        'state' => '20',
                        "children" => [],
                    ],
                    [
                        "title" => "权限菜单-删除",
                        "path" => "admin/AdminRule/del",
                        "method" => "GET",
                        "type" => "30",
                        "icon" => "",
                        "params" => "",
                        "is_show" => 10,
                        "is_system" => 20,
                        'state' => '20',
                        "children" => [],
                    ],
                    [
                        "title" => "权限菜单-编辑列",
                        "path" => "admin/AdminRule/rowEdit",
                        "method" => "GET",
                        "type" => "30",
                        "icon" => "",
                        "params" => "",
                        "is_show" => 10,
                        "is_system" => 20,
                        'state' => '20',
                        "children" => [],
                    ],
                    [
                        "title" => "权限菜单-资源",
                        "path" => "admin/AdminRule/resources",
                        "method" => "GET",
                        "type" => "30",
                        "icon" => "",
                        "params" => "",
                        "is_show" => 10,
                        "is_system" => 20,
                        'state' => '20',
                        "children" => [],
                    ],
                ],
            ],
        ],
    ],
    [
        'title' => '系统配置',
        'path' => 'Config',
        'method' => 'GET',
        'type' => '10',
        'icon' => 'Setting',
        'params' => '',
        'is_show' => '20',
        'is_system' => '10',
        'is_web' => '10',
        'state' => '20',
        'sort' => 9999,
        'children' => [
            [
                'title' => '系统设置',
                'path' => 'admin/Setting/system',
                'method' => 'GET',
                'type' => '20',
                'icon' => '',
                'params' => '',
                'is_show' => '20',
                'is_system' => '10',
                'is_web' => '10',
                'state' => '20',
                'sort' => 1,
                'children' => [],
            ],
            [
                'title' => '备案设置',
                'path' => 'admin/Setting/webicp',
                'method' => 'GET',
                'type' => '20',
                'icon' => '',
                'params' => '',
                'is_show' => '20',
                'is_system' => '10',
                'is_web' => '10',
                'state' => '20',
                'sort' => 2,
                'children' => [],
            ],
        ],
    ],
];