<?php

return [
    [
        "title" => "工作台",
        "path" => "workbench",
        "type" => "20",
        "icon" => "DashboardOutlined",
        "params" => "",
        "is_show" => 20,
        'is_saas' => '10',
        'state' => '20',
        "sort" => 1,
        "pid" => "",
        "children" => [
            [
                "title" => "获取应用信息",
                "path" => "admin/Index/site",
                "type" => "30",
                "icon" => "",
                "params" => "",
                "is_show" => 10,
                "is_system" => 20,
                'is_saas' => '10',
                'state' => '20',
            ],
            [
                "title" => "系统登录",
                "path" => "admin/Publics/login",
                "method" => "POST",
                "type" => "30",
                "icon" => "",
                "params" => "",
                "is_show" => 10,
                "is_system" => 20,
                'is_saas' => '10',
                'state' => '20',
            ],
            [
                "title" => "退出登录",
                "path" => "admin/Publics/logout",
                "method" => "POST",
                "type" => "30",
                "icon" => "",
                "params" => "",
                "is_show" => 10,
                "is_system" => 20,
                'is_saas' => '10',
                'state' => '20',
            ],
            [
                "title" => "获取用户信息",
                "path" => "admin/Publics/user",
                "method" => "GET",
                "type" => "30",
                "icon" => "",
                "params" => "",
                "is_show" => 10,
                "is_system" => 20,
                'is_saas' => '10',
                'state' => '20',
            ],
        ],
    ],
    [
        // 插件标题
        "title" => "插件管理",
        // 插件短标题
        'short_title' => '插件',
        // 插件地址
        "path" => "Plugins",
        // 请求方式，可以是数组或字符串，字符串示例: GET,POST,PUT,DELETE
        "method" => "GET",
        // 菜单类型：10目录，20菜单，30:按钮
        "type" => "10",
        // 菜单图标
        "icon" => "AppstoreOutlined",
        // 菜单参数，组件类型是远程组件时，该处写组件接口地址
        "params" => "",
        // 是否显示：10隐藏，20显示
        "is_show" => 20,
        'is_saas' => '10',
        'state' => '20',
        // 菜单排序，默认值越小越靠前
        "sort" => 20,
        // 父级菜单地址，不填写或不存在时为顶级菜单
        "pid" => "",
        // 继续添加子菜单
        "children" => [
            [
                // 以下参数如上，pid自动获取当前父级菜单地址
                "title" => "本地插件",
                "path" => "admin/Plugins/index",
                "type" => "20",
                "icon" => "",
                "params" => '',
                "is_show" => 20,
                'is_saas' => '10',
                'state' => '20',
                'sort' => 1,
                "children" => [
                ],
            ],
        ],
    ],
    [
        "title" => "权限管理",
        "path" => "Auth",
        "method" => "GET",
        "type" => "10",
        "icon" => "TeamOutlined",
        "params" => "",
        "is_show" => 20,
        "is_system" => 20,
        'is_saas' => '10',
        'state' => '20',
        "sort" => 8888,
        "pid" => "",
        "children" => [
            [
                "title" => "账号管理",
                "path" => "admin/Admin/index",
                "method" => "GET",
                "type" => "20",
                "icon" => "",
                "params" => "",
                "is_show" => 20,
                "is_system" => 20,
                'is_saas' => '10',
                'state' => '20',
                "children" => [
                    [
                        "title" => "账号管理-添加",
                        "path" => "admin/Admin/add",
                        "method" => "GET",
                        "type" => "30",
                        "icon" => "",
                        "params" => "",
                        "is_show" => 10,
                        "is_system" => 20,
                        'is_saas' => '10',
                        'state' => '20',
                        "children" => [],
                    ],
                    [
                        "title" => "账号管理-修改",
                        "path" => "admin/Admin/edit",
                        "method" => "GET",
                        "type" => "30",
                        "icon" => "",
                        "params" => "",
                        "is_show" => 10,
                        "is_system" => 20,
                        'is_saas' => '10',
                        'state' => '20',
                        "children" => [],
                    ],
                    [
                        "title" => "账号管理-删除",
                        "path" => "admin/Admin/del",
                        "method" => "GET",
                        "type" => "30",
                        "icon" => "",
                        "params" => "",
                        "is_show" => 10,
                        "is_system" => 20,
                        'is_saas' => '10',
                        'state' => '20',
                        "children" => [],
                    ],
                    [
                        "title" => "账号管理-编辑列",
                        "path" => "admin/Admin/rowEdit",
                        "method" => "GET",
                        "type" => "30",
                        "icon" => "",
                        "params" => "",
                        "is_show" => 10,
                        "is_system" => 20,
                        'is_saas' => '10',
                        'state' => '20',
                        "children" => [],
                    ],
                    [
                        "title" => "账号管理-资料",
                        "path" => "admin/Admin/profile",
                        "method" => "GET",
                        "type" => "30",
                        "icon" => "",
                        "params" => "",
                        "is_show" => 10,
                        "is_system" => 20,
                        'is_saas' => '10',
                        'state' => '20',
                        "children" => [],
                    ],
                ],
            ],
            [
                "title" => "角色管理",
                "path" => "admin/AdminRole/index",
                "method" => "GET",
                "type" => "20",
                "icon" => "",
                "params" => "",
                "is_show" => 20,
                "is_system" => 20,
                'is_saas' => '10',
                'state' => '20',
                "children" => [
                    [
                        "title" => "角色管理-添加",
                        "path" => "admin/AdminRole/add",
                        "method" => "GET",
                        "type" => "30",
                        "icon" => "",
                        "params" => "",
                        "is_show" => 10,
                        "is_system" => 20,
                        'is_saas' => '10',
                        'state' => '20',
                        "children" => [],
                    ],
                    [
                        "title" => "角色管理-修改",
                        "path" => "admin/AdminRole/edit",
                        "method" => "GET",
                        "type" => "30",
                        "icon" => "",
                        "params" => "",
                        "is_show" => 10,
                        "is_system" => 20,
                        'is_saas' => '10',
                        'state' => '20',
                        "children" => [],
                    ],
                    [
                        "title" => "角色管理-删除",
                        "path" => "admin/AdminRole/del",
                        "method" => "GET",
                        "type" => "30",
                        "icon" => "",
                        "params" => "",
                        "is_show" => 10,
                        "is_system" => 20,
                        'is_saas' => '10',
                        'state' => '20',
                        "children" => [],
                    ],
                    [
                        "title" => "角色管理-授权",
                        "path" => "admin/AdminRole/auth",
                        "method" => "GET,PUT",
                        "type" => "30",
                        "icon" => "",
                        "params" => "",
                        "is_show" => 10,
                        "is_system" => 20,
                        'is_saas' => '10',
                        'state' => '20',
                        "children" => [],
                    ],
                ],
            ],
            [
                "title" => "权限菜单",
                "path" => "admin/AdminRule/index",
                "method" => "GET",
                "type" => "20",
                "icon" => "",
                "params" => "",
                "is_show" => 20,
                "is_system" => 20,
                'is_saas' => '10',
                'state' => '20',
                "children" => [
                    [
                        "title" => "权限菜单-添加",
                        "path" => "admin/AdminRule/add",
                        "method" => "GET",
                        "type" => "30",
                        "icon" => "",
                        "params" => "",
                        "is_show" => 10,
                        "is_system" => 20,
                        'is_saas' => '10',
                        'state' => '20',
                        "children" => [],
                    ],
                    [
                        "title" => "权限菜单-修改",
                        "path" => "admin/AdminRule/edit",
                        "method" => "GET",
                        "type" => "30",
                        "icon" => "",
                        "params" => "",
                        "is_show" => 10,
                        "is_system" => 20,
                        'is_saas' => '10',
                        'state' => '20',
                        "children" => [],
                    ],
                    [
                        "title" => "权限菜单-删除",
                        "path" => "admin/AdminRule/del",
                        "method" => "GET",
                        "type" => "30",
                        "icon" => "",
                        "params" => "",
                        "is_show" => 10,
                        "is_system" => 20,
                        'is_saas' => '10',
                        'state' => '20',
                        "children" => [],
                    ],
                    [
                        "title" => "权限菜单-编辑列",
                        "path" => "admin/AdminRule/rowEdit",
                        "method" => "GET",
                        "type" => "30",
                        "icon" => "",
                        "params" => "",
                        "is_show" => 10,
                        "is_system" => 20,
                        'is_saas' => '10',
                        'state' => '20',
                        "children" => [],
                    ],
                    [
                        "title" => "权限菜单-资源",
                        "path" => "admin/AdminRule/resources",
                        "method" => "GET",
                        "type" => "30",
                        "icon" => "",
                        "params" => "",
                        "is_show" => 10,
                        "is_system" => 20,
                        'is_saas' => '10',
                        'state' => '20',
                        "children" => [],
                    ],
                ],
            ],
        ],
    ],
    [
        'title' => '系统配置',
        'path' => 'Config',
        'method' => 'GET',
        'type' => '10',
        'icon' => 'Setting',
        'params' => '',
        'is_show' => '20',
        'is_system' => '10',
        'is_web' => '10',
        'state' => '20',
        'sort' => 9999,
        'children' => [
            [
                'title' => '系统设置',
                'path' => 'admin/Setting/system',
                'component' => 'form/index',
                'method' => 'GET',
                'type' => '20',
                'icon' => '',
                'params' => '',
                'is_show' => '20',
                'is_system' => '10',
                'is_web' => '10',
                'state' => '20',
                'sort' => 1,
                'children' => [],
            ],
            [
                'title' => '版权设置',
                'path' => 'admin/Setting/copyright',
                'component' => 'form/index',
                'method' => 'GET',
                'type' => '20',
                'icon' => '',
                'params' => '',
                'is_show' => '20',
                'is_system' => '10',
                'is_web' => '10',
                'state' => '20',
                'sort' => 2,
                'children' => [],
            ],
        ],
    ],
];