<?php

return [
  [
    'title' => '系统配置',
    'path' => 'Config',
    'method' => 'GET',
    'type' => '10',
    'icon' => 'Setting',
    'params' => '',
    'is_show' => '20',
    'is_saas' => '10',
    'is_system' => '10',
    'state' => '20',
    'sort' => 9999,
    'children' => [
      [
        'title' => '上传设置',
        'path' => 'admin/Engine/index',
        'method' => 'GET',
        'type' => '20',
        'icon' => '',
        'params' => '',
        'is_show' => '20',
        'is_system' => '10',
        'is_saas' => '10',
        'state' => '20',
        'sort' => 20,
        'children' => [
          [
            'title' => '保存上传设置',
            'path' => 'admin/Engine/config',
            'method' => 'GET',
            'type' => '30',
            'icon' => '',
            'params' => '',
            'is_show' => '10',
            'is_system' => '10',
            'is_saas' => '10',
            'state' => '20',
            'children' => [],
          ],
          [
            'title' => '文件管理',
            'path' => 'admin/Upload/index',
            'method' => 'GET',
            'type' => '30',
            'icon' => '',
            'params' => '',
            'is_show' => '10',
            'is_system' => '10',
            'is_saas' => '10',
            'state' => '20',
            'children' => [
              [
                'title' => '上传文件',
                'path' => 'admin/Upload/upload',
                'method' => 'GET',
                'type' => '30',
                'icon' => '',
                'params' => '',
                'is_show' => '10',
                'is_system' => '10',
                'is_saas' => '10',
                'state' => '20',
                'children' => [],
              ],
              [
                'title' => '修改文件',
                'path' => 'admin/Upload/edit',
                'method' => 'GET',
                'type' => '30',
                'icon' => '',
                'params' => '',
                'is_show' => '10',
                'is_system' => '10',
                'is_saas' => '10',
                'state' => '20',
                'children' => [],
              ],
              [
                'title' => '删除文件',
                'path' => 'admin/Upload/del',
                'method' => 'GET',
                'type' => '30',
                'icon' => '',
                'params' => '',
                'is_show' => '10',
                'is_system' => '10',
                'is_saas' => '10',
                'state' => '20',
                'children' => [],
              ],
              [
                'title' => '查看文件',
                'path' => 'admin/Upload/show',
                'method' => 'GET',
                'type' => '30',
                'icon' => '',
                'params' => '',
                'is_show' => '10',
                'is_system' => '10',
                'is_saas' => '10',
                'state' => '20',
                'children' => [],
              ],
            ],
          ],
        ],
      ],
    ],
  ],
];