<?php
/**
 * xbAdmin 后台菜单（权限规则）定义
 *
 * 安装时由 api/Install.php 调用 Menus::install() 同步写入 xb_admin_rule。
 * 约定说明：
 * 1. is_show/type/state/is_system/is_default 必须使用字符串 '10'/'20'，Menus::install() 做严格比对；
 * 2. state 不填会被置为 '10'（停用），因此每一级都必须显式声明 '20'；
 * 3. path 口径为「模块/控制器/方法」，与 xbAdminPathInfo() 的返回值一致；
 * 4. is_default=20 的权限会自动授予新建角色，只放登录链路必需的基础接口；
 * 5. 未出现在这里的接口默认拒绝访问（超级管理员除外），新增控制器方法需同步补行。
 */
return [
    [
        'title' => '工作台',
        'path' => 'workbench',
        'method' => 'GET',
        'type' => '20',
        'icon' => 'DashboardOutlined',
        'params' => [
            'url' => 'admin/Index/workbench',
        ],
        'is_show' => '20',
        'is_system' => '20',
        'is_default' => '20',
        'state' => '20',
        'sort' => 1,
        'children' => [
            [
                'title' => '获取站点信息',
                'path' => 'admin/Index/site',
                'method' => 'GET',
                'type' => '30',
                'icon' => '',
                'params' => '',
                'is_show' => '10',
                'is_system' => '20',
                'is_default' => '20',
                'state' => '20',
                'sort' => 1,
            ],
            [
                'title' => '获取顶部工具栏',
                'path' => 'admin/Index/toolbar',
                'method' => 'GET',
                'type' => '30',
                'icon' => '',
                'params' => '',
                'is_show' => '10',
                'is_system' => '20',
                'is_default' => '20',
                'state' => '20',
                'sort' => 2,
            ],
            [
                'title' => '系统登录',
                'path' => 'admin/Publics/login',
                'method' => 'POST',
                'type' => '30',
                'icon' => '',
                'params' => '',
                'is_show' => '10',
                'is_system' => '20',
                'is_default' => '20',
                'state' => '20',
                'sort' => 3,
            ],
            [
                'title' => '登录验证码',
                'path' => 'admin/Publics/captcha',
                'method' => 'GET',
                'type' => '30',
                'icon' => '',
                'params' => '',
                'is_show' => '10',
                'is_system' => '20',
                'is_default' => '20',
                'state' => '20',
                'sort' => 4,
            ],
            [
                'title' => '退出登录',
                'path' => 'admin/Publics/logout',
                'method' => 'POST',
                'type' => '30',
                'icon' => '',
                'params' => '',
                'is_show' => '10',
                'is_system' => '20',
                'is_default' => '20',
                'state' => '20',
                'sort' => 5,
            ],
            [
                'title' => '续签登录令牌',
                'path' => 'admin/Publics/refresh',
                'method' => 'POST',
                'type' => '30',
                'icon' => '',
                'params' => '',
                'is_show' => '10',
                'is_system' => '20',
                'is_default' => '20',
                'state' => '20',
                'sort' => 6,
            ],
            [
                'title' => '获取当前用户',
                'path' => 'admin/Publics/user',
                'method' => 'GET',
                'type' => '30',
                'icon' => '',
                'params' => '',
                'is_show' => '10',
                'is_system' => '20',
                'is_default' => '20',
                'state' => '20',
                'sort' => 7,
            ],
            [
                'title' => '获取导航菜单',
                'path' => 'admin/Publics/menus',
                'method' => 'GET',
                'type' => '30',
                'icon' => '',
                'params' => '',
                'is_show' => '10',
                'is_system' => '20',
                'is_default' => '20',
                'state' => '20',
                'sort' => 8,
            ],
            [
                'title' => '获取布局配置',
                'path' => 'admin/Publics/layouts',
                'method' => 'GET',
                'type' => '30',
                'icon' => '',
                'params' => '',
                'is_show' => '10',
                'is_system' => '20',
                'is_default' => '20',
                'state' => '20',
                'sort' => 9,
            ],
            [
                'title' => '个人资料',
                'path' => 'admin/Admin/profile',
                'method' => 'GET',
                'type' => '30',
                'icon' => '',
                'params' => '',
                'is_show' => '10',
                'is_system' => '20',
                'is_default' => '20',
                'state' => '20',
                'sort' => 10,
            ],
        ],
    ],
    [
        'title' => '权限管理',
        'path' => 'Permission',
        'method' => 'GET',
        'type' => '10',
        'icon' => 'SafetyOutlined',
        'params' => '',
        'is_show' => '20',
        'is_system' => '20',
        'is_default' => '10',
        'state' => '20',
        'sort' => 100,
        'children' => [
            [
                'title' => '管理员管理',
                'path' => 'admin/Admin/index',
                'method' => 'GET',
                'type' => '20',
                'icon' => 'UserOutlined',
                'params' => '',
                'is_show' => '20',
                'is_system' => '20',
                'is_default' => '10',
                'state' => '20',
                'sort' => 1,
                'children' => [
                    [
                        'title' => '管理员-新增',
                        'path' => 'admin/Admin/add',
                        'method' => ['GET', 'POST'],
                        'type' => '30',
                        'icon' => '',
                        'params' => '',
                        'is_show' => '10',
                        'is_system' => '20',
                        'is_default' => '10',
                        'state' => '20',
                        'sort' => 1,
                    ],
                    [
                        'title' => '管理员-修改',
                        'path' => 'admin/Admin/edit',
                        'method' => ['GET', 'PUT'],
                        'type' => '30',
                        'icon' => '',
                        'params' => '',
                        'is_show' => '10',
                        'is_system' => '20',
                        'is_default' => '10',
                        'state' => '20',
                        'sort' => 2,
                    ],
                    [
                        'title' => '管理员-快捷编辑',
                        'path' => 'admin/Admin/rowEdit',
                        'method' => 'POST',
                        'type' => '30',
                        'icon' => '',
                        'params' => '',
                        'is_show' => '10',
                        'is_system' => '20',
                        'is_default' => '10',
                        'state' => '20',
                        'sort' => 3,
                    ],
                    [
                        'title' => '管理员-删除',
                        'path' => 'admin/Admin/del',
                        'method' => 'DELETE',
                        'type' => '30',
                        'icon' => '',
                        'params' => '',
                        'is_show' => '10',
                        'is_system' => '20',
                        'is_default' => '10',
                        'state' => '20',
                        'sort' => 4,
                    ],
                ],
            ],
            [
                'title' => '角色管理',
                'path' => 'admin/AdminRole/index',
                'method' => 'GET',
                'type' => '20',
                'icon' => 'TeamOutlined',
                'params' => '',
                'is_show' => '20',
                'is_system' => '20',
                'is_default' => '10',
                'state' => '20',
                'sort' => 2,
                'children' => [
                    [
                        'title' => '角色管理-新增',
                        'path' => 'admin/AdminRole/add',
                        'method' => ['GET', 'POST'],
                        'type' => '30',
                        'icon' => '',
                        'params' => '',
                        'is_show' => '10',
                        'is_system' => '20',
                        'is_default' => '10',
                        'state' => '20',
                        'sort' => 1,
                    ],
                    [
                        'title' => '角色管理-修改',
                        'path' => 'admin/AdminRole/edit',
                        'method' => ['GET', 'PUT'],
                        'type' => '30',
                        'icon' => '',
                        'params' => '',
                        'is_show' => '10',
                        'is_system' => '20',
                        'is_default' => '10',
                        'state' => '20',
                        'sort' => 2,
                    ],
                    [
                        'title' => '角色管理-分配权限',
                        'path' => 'admin/AdminRole/auth',
                        'method' => ['GET', 'PUT'],
                        'type' => '30',
                        'icon' => '',
                        'params' => '',
                        'is_show' => '10',
                        'is_system' => '20',
                        'is_default' => '10',
                        'state' => '20',
                        'sort' => 3,
                    ],
                    [
                        'title' => '角色管理-删除',
                        'path' => 'admin/AdminRole/del',
                        'method' => 'DELETE',
                        'type' => '30',
                        'icon' => '',
                        'params' => '',
                        'is_show' => '10',
                        'is_system' => '20',
                        'is_default' => '10',
                        'state' => '20',
                        'sort' => 4,
                    ],
                ],
            ],
            [
                'title' => '菜单权限',
                'path' => 'admin/AdminRule/index',
                'method' => 'GET',
                'type' => '20',
                'icon' => 'MenuOutlined',
                'params' => '',
                'is_show' => '20',
                'is_system' => '20',
                'is_default' => '10',
                'state' => '20',
                'sort' => 3,
                'children' => [
                    [
                        'title' => '菜单权限-新增',
                        'path' => 'admin/AdminRule/add',
                        'method' => ['GET', 'POST'],
                        'type' => '30',
                        'icon' => '',
                        'params' => '',
                        'is_show' => '10',
                        'is_system' => '20',
                        'is_default' => '10',
                        'state' => '20',
                        'sort' => 1,
                    ],
                    [
                        'title' => '菜单权限-修改',
                        'path' => 'admin/AdminRule/edit',
                        'method' => ['GET', 'PUT'],
                        'type' => '30',
                        'icon' => '',
                        'params' => '',
                        'is_show' => '10',
                        'is_system' => '20',
                        'is_default' => '10',
                        'state' => '20',
                        'sort' => 2,
                    ],
                    [
                        'title' => '菜单权限-快捷编辑',
                        'path' => 'admin/AdminRule/rowEdit',
                        'method' => 'POST',
                        'type' => '30',
                        'icon' => '',
                        'params' => '',
                        'is_show' => '10',
                        'is_system' => '20',
                        'is_default' => '10',
                        'state' => '20',
                        'sort' => 3,
                    ],
                    [
                        'title' => '菜单权限-删除',
                        'path' => 'admin/AdminRule/del',
                        'method' => 'DELETE',
                        'type' => '30',
                        'icon' => '',
                        'params' => '',
                        'is_show' => '10',
                        'is_system' => '20',
                        'is_default' => '10',
                        'state' => '20',
                        'sort' => 4,
                    ],
                ],
            ],
        ],
    ],
];
