<?php

return [
    [
        'title' => '工作台',
        'path' => 'workbench',
        'method' => 'GET',
        'type' => '20',
        'icon' => 'DashboardOutlined',
        'params' => [
            'url' => 'admin/Index/workbench',
        ],
        'is_show' => '20',
        'is_system' => '20',
        'is_default' => '20',
        'state' => '20',
        'sort' => 1,
        'children' => [
            [
                'title' => '获取站点信息',
                'path' => 'admin/Index/site',
                'method' => 'GET',
                'type' => '30',
                'icon' => '',
                'params' => '',
                'is_show' => '10',
                'is_system' => '20',
                'is_default' => '20',
                'state' => '20',
                'sort' => 1,
            ],
            [
                'title' => '获取顶部工具栏',
                'path' => 'admin/Index/toolbar',
                'method' => 'GET',
                'type' => '30',
                'icon' => '',
                'params' => '',
                'is_show' => '10',
                'is_system' => '20',
                'is_default' => '20',
                'state' => '20',
                'sort' => 2,
            ],
            [
                'title' => '系统登录',
                'path' => 'admin/Publics/login',
                'method' => 'POST',
                'type' => '30',
                'icon' => '',
                'params' => '',
                'is_show' => '10',
                'is_system' => '20',
                'is_default' => '20',
                'state' => '20',
                'sort' => 3,
            ],
            [
                'title' => '登录验证码',
                'path' => 'admin/Publics/captcha',
                'method' => 'GET',
                'type' => '30',
                'icon' => '',
                'params' => '',
                'is_show' => '10',
                'is_system' => '20',
                'is_default' => '20',
                'state' => '20',
                'sort' => 4,
            ],
            [
                'title' => '退出登录',
                'path' => 'admin/Publics/logout',
                'method' => 'POST',
                'type' => '30',
                'icon' => '',
                'params' => '',
                'is_show' => '10',
                'is_system' => '20',
                'is_default' => '20',
                'state' => '20',
                'sort' => 5,
            ],
            [
                'title' => '续签登录令牌',
                'path' => 'admin/Publics/refresh',
                'method' => 'POST',
                'type' => '30',
                'icon' => '',
                'params' => '',
                'is_show' => '10',
                'is_system' => '20',
                'is_default' => '20',
                'state' => '20',
                'sort' => 6,
            ],
            [
                'title' => '获取当前用户',
                'path' => 'admin/Publics/user',
                'method' => 'GET',
                'type' => '30',
                'icon' => '',
                'params' => '',
                'is_show' => '10',
                'is_system' => '20',
                'is_default' => '20',
                'state' => '20',
                'sort' => 7,
            ],
            [
                'title' => '获取导航菜单',
                'path' => 'admin/Publics/menus',
                'method' => 'GET',
                'type' => '30',
                'icon' => '',
                'params' => '',
                'is_show' => '10',
                'is_system' => '20',
                'is_default' => '20',
                'state' => '20',
                'sort' => 8,
            ],
            [
                'title' => '获取布局配置',
                'path' => 'admin/Publics/layouts',
                'method' => 'GET',
                'type' => '30',
                'icon' => '',
                'params' => '',
                'is_show' => '10',
                'is_system' => '20',
                'is_default' => '20',
                'state' => '20',
                'sort' => 9,
            ],
            [
                'title' => '个人资料',
                'path' => 'admin/Admin/profile',
                'method' => 'GET',
                'type' => '30',
                'icon' => '',
                'params' => '',
                'is_show' => '10',
                'is_system' => '20',
                'is_default' => '20',
                'state' => '20',
                'sort' => 10,
            ],
        ],
    ],
    [
        'title' => '权限管理',
        'path' => 'Permission',
        'method' => 'GET',
        'type' => '10',
        'icon' => 'SafetyOutlined',
        'params' => '',
        'is_show' => '20',
        'is_system' => '20',
        'is_default' => '10',
        'state' => '20',
        'sort' => 100,
        'children' => [
            [
                'title' => '管理人员',
                'path' => 'admin/Admin/index',
                'method' => 'GET',
                'type' => '20',
                'icon' => 'UserOutlined',
                'params' => '',
                'is_show' => '20',
                'is_system' => '20',
                'is_default' => '10',
                'state' => '20',
                'sort' => 1,
                'children' => [
                    [
                        'title' => '管理人员-新增',
                        'path' => 'admin/Admin/add',
                        'method' => ['GET', 'POST'],
                        'type' => '30',
                        'icon' => '',
                        'params' => '',
                        'is_show' => '10',
                        'is_system' => '20',
                        'is_default' => '10',
                        'state' => '20',
                        'sort' => 1,
                    ],
                    [
                        'title' => '管理人员-修改',
                        'path' => 'admin/Admin/edit',
                        'method' => ['GET', 'PUT'],
                        'type' => '30',
                        'icon' => '',
                        'params' => '',
                        'is_show' => '10',
                        'is_system' => '20',
                        'is_default' => '10',
                        'state' => '20',
                        'sort' => 2,
                    ],
                    [
                        'title' => '管理人员-快捷编辑',
                        'path' => 'admin/Admin/rowEdit',
                        'method' => 'POST',
                        'type' => '30',
                        'icon' => '',
                        'params' => '',
                        'is_show' => '10',
                        'is_system' => '20',
                        'is_default' => '10',
                        'state' => '20',
                        'sort' => 3,
                    ],
                    [
                        'title' => '管理人员-删除',
                        'path' => 'admin/Admin/del',
                        'method' => 'DELETE',
                        'type' => '30',
                        'icon' => '',
                        'params' => '',
                        'is_show' => '10',
                        'is_system' => '20',
                        'is_default' => '10',
                        'state' => '20',
                        'sort' => 4,
                    ],
                ],
            ],
            [
                'title' => '部门管理',
                'path' => 'admin/AdminRole/index',
                'method' => 'GET',
                'type' => '20',
                'icon' => 'TeamOutlined',
                'params' => '',
                'is_show' => '20',
                'is_system' => '20',
                'is_default' => '10',
                'state' => '20',
                'sort' => 2,
                'children' => [
                    [
                        'title' => '部门管理-新增',
                        'path' => 'admin/AdminRole/add',
                        'method' => ['GET', 'POST'],
                        'type' => '30',
                        'icon' => '',
                        'params' => '',
                        'is_show' => '10',
                        'is_system' => '20',
                        'is_default' => '10',
                        'state' => '20',
                        'sort' => 1,
                    ],
                    [
                        'title' => '部门管理-修改',
                        'path' => 'admin/AdminRole/edit',
                        'method' => ['GET', 'PUT'],
                        'type' => '30',
                        'icon' => '',
                        'params' => '',
                        'is_show' => '10',
                        'is_system' => '20',
                        'is_default' => '10',
                        'state' => '20',
                        'sort' => 2,
                    ],
                    [
                        'title' => '部门管理-分配权限',
                        'path' => 'admin/AdminRole/auth',
                        'method' => ['GET', 'PUT'],
                        'type' => '30',
                        'icon' => '',
                        'params' => '',
                        'is_show' => '10',
                        'is_system' => '20',
                        'is_default' => '10',
                        'state' => '20',
                        'sort' => 3,
                    ],
                    [
                        'title' => '部门管理-删除',
                        'path' => 'admin/AdminRole/del',
                        'method' => 'DELETE',
                        'type' => '30',
                        'icon' => '',
                        'params' => '',
                        'is_show' => '10',
                        'is_system' => '20',
                        'is_default' => '10',
                        'state' => '20',
                        'sort' => 4,
                    ],
                    [
                        'title' => '部门管理-主题设置',
                        'path' => 'admin/AdminRole/theme',
                        'method' => ['GET', 'PUT'],
                        'type' => '30',
                        'icon' => '',
                        'params' => '',
                        'is_show' => '10',
                        'is_system' => '20',
                        'is_default' => '10',
                        'state' => '20',
                        'sort' => 5,
                    ],
                ],
            ],
            [
                'title' => '菜单权限',
                'path' => 'admin/AdminRule/index',
                'method' => 'GET',
                'type' => '20',
                'icon' => 'MenuOutlined',
                'params' => '',
                'is_show' => '20',
                'is_system' => '20',
                'is_default' => '10',
                'state' => '20',
                'sort' => 3,
                'children' => [
                    [
                        'title' => '菜单权限-新增',
                        'path' => 'admin/AdminRule/add',
                        'method' => ['GET', 'POST'],
                        'type' => '30',
                        'icon' => '',
                        'params' => '',
                        'is_show' => '10',
                        'is_system' => '20',
                        'is_default' => '10',
                        'state' => '20',
                        'sort' => 1,
                    ],
                    [
                        'title' => '菜单权限-修改',
                        'path' => 'admin/AdminRule/edit',
                        'method' => ['GET', 'PUT'],
                        'type' => '30',
                        'icon' => '',
                        'params' => '',
                        'is_show' => '10',
                        'is_system' => '20',
                        'is_default' => '10',
                        'state' => '20',
                        'sort' => 2,
                    ],
                    [
                        'title' => '菜单权限-快捷编辑',
                        'path' => 'admin/AdminRule/rowEdit',
                        'method' => 'POST',
                        'type' => '30',
                        'icon' => '',
                        'params' => '',
                        'is_show' => '10',
                        'is_system' => '20',
                        'is_default' => '10',
                        'state' => '20',
                        'sort' => 3,
                    ],
                    [
                        'title' => '菜单权限-删除',
                        'path' => 'admin/AdminRule/del',
                        'method' => 'DELETE',
                        'type' => '30',
                        'icon' => '',
                        'params' => '',
                        'is_show' => '10',
                        'is_system' => '20',
                        'is_default' => '10',
                        'state' => '20',
                        'sort' => 4,
                    ],
                ],
            ],
        ],
    ],
    [
        'title' => '系统管理',
        'path' => 'System',
        'method' => 'GET',
        'type' => '10',
        'icon' => 'Setting',
        'params' => '',
        'is_show' => '20',
        'is_system' => '20',
        'is_default' => '10',
        'state' => '20',
        'sort' => 100,
        'children' => [
            [
                'title' => '系统设置',
                'path' => 'admin/Config/index',
                'method' => 'GET',
                'type' => '20',
                'icon' => 'SettingOutlined',
                'params' => '',
                'is_show' => '20',
                'is_system' => '20',
                'is_default' => '10',
                'state' => '20',
                'sort' => 1,
                'children' => [
                    [
                        'title' => '读取配置项',
                        'path' => 'admin/Config/detail',
                        'method' => 'GET',
                        'type' => '30',
                        'icon' => '',
                        'params' => '',
                        'is_show' => '10',
                        'is_system' => '20',
                        'is_default' => '10',
                        'state' => '20',
                        'sort' => 1,
                    ],
                    [
                        'title' => '写入配置项',
                        'path' => 'admin/Config/update',
                        'method' => 'POST',
                        'type' => '30',
                        'icon' => '',
                        'params' => '',
                        'is_show' => '10',
                        'is_system' => '20',
                        'is_default' => '10',
                        'state' => '20',
                        'sort' => 2,
                    ],
                    [
                        'title' => '上报配置分组',
                        'path' => 'admin/Config/report',
                        'method' => 'POST',
                        'type' => '30',
                        'icon' => '',
                        'params' => '',
                        'is_show' => '10',
                        'is_system' => '20',
                        'is_default' => '10',
                        'state' => '20',
                        'sort' => 3,
                    ],
                ],
            ],
            [
                'title' => '上传设置',
                'path' => 'admin/Engine/index',
                'method' => 'GET',
                'type' => '20',
                'icon' => 'CloudUploadOutlined',
                'params' => '',
                'is_show' => '20',
                'is_system' => '20',
                'is_default' => '10',
                'state' => '20',
                'sort' => 5,
                'children' => [
                    [
                        'title' => '文件管理',
                        'path' => 'admin/Upload/index',
                        'method' => 'GET',
                        'type' => '30',
                        'icon' => 'FolderOutlined',
                        'params' => '',
                        'is_show' => '10',
                        'is_system' => '20',
                        'is_default' => '10',
                        'state' => '20',
                        'sort' => 1,
                        'children' => [
                            [
                                'title' => '上传文件',
                                'path' => 'admin/Upload/upload',
                                'method' => 'GET',
                                'type' => '30',
                                'icon' => '',
                                'params' => '',
                                'is_show' => '10',
                                'is_system' => '20',
                                'is_default' => '10',
                                'state' => '20',
                                'sort' => 1,
                            ],
                            [
                                'title' => '上传附件',
                                'path' => 'api/Upload/upload',
                                'method' => 'POST',
                                'type' => '30',
                                'icon' => '',
                                'params' => '',
                                'is_show' => '10',
                                'is_system' => '20',
                                'is_default' => '10',
                                'state' => '20',
                                'sort' => 2,
                            ],
                            [
                                'title' => '分片上传',
                                'path' => 'api/Upload/chunk',
                                'method' => 'POST',
                                'type' => '30',
                                'icon' => '',
                                'params' => '',
                                'is_show' => '10',
                                'is_system' => '20',
                                'is_default' => '10',
                                'state' => '20',
                                'sort' => 3,
                            ],
                            [
                                'title' => '修改文件',
                                'path' => 'admin/Upload/edit',
                                'method' => ['GET', 'PUT'],
                                'type' => '30',
                                'icon' => '',
                                'params' => '',
                                'is_show' => '10',
                                'is_system' => '20',
                                'is_default' => '10',
                                'state' => '20',
                                'sort' => 4,
                            ],
                            [
                                'title' => '查看文件',
                                'path' => 'admin/Upload/show',
                                'method' => 'GET',
                                'type' => '30',
                                'icon' => '',
                                'params' => '',
                                'is_show' => '10',
                                'is_system' => '20',
                                'is_default' => '10',
                                'state' => '20',
                                'sort' => 5,
                            ],
                            [
                                'title' => '删除文件',
                                'path' => 'admin/Upload/del',
                                'method' => ['GET', 'DELETE'],
                                'type' => '30',
                                'icon' => '',
                                'params' => '',
                                'is_show' => '10',
                                'is_system' => '20',
                                'is_default' => '10',
                                'state' => '20',
                                'sort' => 6,
                            ],
                        ],
                    ],
                    [
                        'title' => '保存上传设置',
                        'path' => 'admin/Engine/config',
                        'method' => ['GET', 'PUT'],
                        'type' => '30',
                        'icon' => '',
                        'params' => '',
                        'is_show' => '10',
                        'is_system' => '20',
                        'is_default' => '10',
                        'state' => '20',
                        'sort' => 2,
                    ],
                    [
                        'title' => '切换默认引擎',
                        'path' => 'admin/Engine/quickSave',
                        'method' => ['GET', 'POST'],
                        'type' => '30',
                        'icon' => '',
                        'params' => '',
                        'is_show' => '10',
                        'is_system' => '20',
                        'is_default' => '10',
                        'state' => '20',
                        'sort' => 3,
                    ],
                ],
            ],
            [
                'title' => '定时任务',
                'path' => 'admin/Crontab/index',
                'method' => 'GET',
                'type' => '20',
                'icon' => 'ClockCircleOutlined',
                'params' => '',
                'is_show' => '20',
                'is_system' => '20',
                'is_default' => '10',
                'state' => '20',
                'sort' => 3,
                'children' => [
                    [
                        'title' => '添加定时任务',
                        'path' => 'admin/Crontab/add',
                        'method' => ['GET', 'POST'],
                        'type' => '30',
                        'icon' => '',
                        'params' => '',
                        'is_show' => '10',
                        'is_system' => '20',
                        'is_default' => '10',
                        'state' => '20',
                        'sort' => 1,
                    ],
                    [
                        'title' => '修改定时任务',
                        'path' => 'admin/Crontab/edit',
                        'method' => ['GET', 'PUT'],
                        'type' => '30',
                        'icon' => '',
                        'params' => '',
                        'is_show' => '10',
                        'is_system' => '20',
                        'is_default' => '10',
                        'state' => '20',
                        'sort' => 2,
                    ],
                    [
                        'title' => '删除定时任务',
                        'path' => 'admin/Crontab/del',
                        'method' => ['GET', 'DELETE'],
                        'type' => '30',
                        'icon' => '',
                        'params' => '',
                        'is_show' => '10',
                        'is_system' => '20',
                        'is_default' => '10',
                        'state' => '20',
                        'sort' => 3,
                    ],
                    [
                        'title' => '导出定时任务',
                        'path' => 'admin/Crontab/export',
                        'method' => 'GET',
                        'type' => '30',
                        'icon' => '',
                        'params' => '',
                        'is_show' => '10',
                        'is_system' => '20',
                        'is_default' => '10',
                        'state' => '20',
                        'sort' => 4,
                    ],
                    [
                        'title' => '任务日志',
                        'path' => 'admin/CrontabLog/index',
                        'method' => 'GET',
                        'type' => '30',
                        'icon' => '',
                        'params' => '',
                        'is_show' => '10',
                        'is_system' => '20',
                        'is_default' => '10',
                        'state' => '20',
                        'sort' => 5,
                    ],
                    [
                        'title' => '清除任务日志',
                        'path' => 'admin/CrontabLog/clear',
                        'method' => 'GET',
                        'type' => '30',
                        'icon' => '',
                        'params' => '',
                        'is_show' => '10',
                        'is_system' => '20',
                        'is_default' => '10',
                        'state' => '20',
                        'sort' => 6,
                    ],
                ],
            ],
            [
                'title' => '字典管理',
                'path' => 'admin/Dict/index',
                'method' => 'GET',
                'type' => '20',
                'icon' => 'BookOutlined',
                'params' => '',
                'is_show' => '20',
                'is_system' => '20',
                'is_default' => '10',
                'state' => '20',
                'sort' => 4,
                'children' => [
                    [
                        'title' => '添加字典',
                        'path' => 'admin/Dict/add',
                        'method' => ['GET', 'POST'],
                        'type' => '30',
                        'icon' => '',
                        'params' => '',
                        'is_show' => '10',
                        'is_system' => '20',
                        'is_default' => '10',
                        'state' => '20',
                        'sort' => 1,
                    ],
                    [
                        'title' => '修改字典',
                        'path' => 'admin/Dict/edit',
                        'method' => ['GET', 'PUT'],
                        'type' => '30',
                        'icon' => '',
                        'params' => '',
                        'is_show' => '10',
                        'is_system' => '20',
                        'is_default' => '10',
                        'state' => '20',
                        'sort' => 2,
                    ],
                    [
                        'title' => '删除字典',
                        'path' => 'admin/Dict/del',
                        'method' => ['GET', 'DELETE'],
                        'type' => '30',
                        'icon' => '',
                        'params' => '',
                        'is_show' => '10',
                        'is_system' => '20',
                        'is_default' => '10',
                        'state' => '20',
                        'sort' => 3,
                    ],
                ],
            ],
            
        ],
    ],
];
