<?php

return [
    [
        "title" => "工作台",
        "path" => "workbench",
        "component" => "workbench/index",
        "method" => "GET",
        "type" => "20",
        "icon" => "DashboardOutlined",
        "params" => "app/xbCode/admin/Index/workbench",
        "is_show" => 20,
        "sort" => 1,
        "pid" => "",
        "children" => [
            [
                "title" => "获取应用信息",
                "path" => "admin/Index/site",
                "component" => "none/index",
                "method" => "GET",
                "type" => "30",
                "icon" => "",
                "params" => "",
                "is_show" => 10,
            ],
            [
                "title" => "系统登录",
                "path" => "admin/Login/login",
                "component" => "none/index",
                "method" => "POST",
                "type" => "30",
                "icon" => "",
                "params" => "",
                "is_show" => 10,
            ],
            [
                "title" => "退出登录",
                "path" => "admin/Login/loginout",
                "component" => "none/index",
                "method" => "POST",
                "type" => "30",
                "icon" => "",
                "params" => "",
                "is_show" => 10,
            ],
            [
                "title" => "获取用户信息",
                "path" => "admin/Login/user",
                "component" => "none/index",
                "method" => "GET",
                "type" => "30",
                "icon" => "",
                "params" => "",
                "is_show" => 10,
            ],
        ],
    ],
    [
        "title" => "权限管理",
        "path" => "Auth",
        "component" => "none/index",
        "method" => "GET",
        "type" => "10",
        "icon" => "TeamOutlined",
        "params" => "",
        "is_show" => 20,
        "sort" => 1,
        "pid" => "",
        "children" => [
            [
                "title" => "账号管理",
                "path" => "admin/Admin/index",
                "component" => "table/index",
                "method" => "GET",
                "type" => "20",
                "icon" => "",
                "params" => "",
                "is_show" => 20,
                "children" => [
                    [
                        "title" => "账号管理-表格",
                        "path" => "admin/Admin/indexTable",
                        "component" => "none/index",
                        "method" => "GET",
                        "type" => "30",
                        "icon" => "",
                        "params" => "",
                        "is_show" => 10,
                        "children" => [],
                    ],
                    [
                        "title" => "账号管理-添加",
                        "path" => "admin/Admin/add",
                        "component" => "form/index",
                        "method" => "GET",
                        "type" => "30",
                        "icon" => "",
                        "params" => "",
                        "is_show" => 10,
                        "children" => [],
                    ],
                    [
                        "title" => "账号管理-修改",
                        "path" => "admin/Admin/edit",
                        "component" => "form/index",
                        "method" => "GET",
                        "type" => "30",
                        "icon" => "",
                        "params" => "",
                        "is_show" => 10,
                        "children" => [],
                    ],
                    [
                        "title" => "账号管理-删除",
                        "path" => "admin/Admin/del",
                        "component" => "none/index",
                        "method" => "GET",
                        "type" => "30",
                        "icon" => "",
                        "params" => "",
                        "is_show" => 10,
                        "children" => [],
                    ],
                    [
                        "title" => "账号管理-编辑列",
                        "path" => "admin/Admin/rowEdit",
                        "component" => "none/index",
                        "method" => "GET,PUT",
                        "type" => "30",
                        "icon" => "",
                        "params" => "",
                        "is_show" => 10,
                        "children" => [],
                    ],
                    [
                        "title" => "账号管理-资料",
                        "path" => "admin/Admin/profile",
                        "component" => "none/index",
                        "method" => "GET,PUT",
                        "type" => "30",
                        "icon" => "",
                        "params" => "",
                        "is_show" => 10,
                        "children" => [],
                    ],
                ],
            ],
            [
                "title" => "角色管理",
                "path" => "admin/AdminRole/index",
                "component" => "table/index",
                "method" => "GET",
                "type" => "20",
                "icon" => "",
                "params" => "",
                "is_show" => 20,
                "children" => [
                    [
                        "title" => "角色管理-表格",
                        "path" => "admin/AdminRole/indexTable",
                        "component" => "none/index",
                        "method" => "GET",
                        "type" => "30",
                        "icon" => "",
                        "params" => "",
                        "is_show" => 10,
                        "children" => [],
                    ],
                    [
                        "title" => "角色管理-添加",
                        "path" => "admin/AdminRole/add",
                        "component" => "form/index",
                        "method" => "GET",
                        "type" => "30",
                        "icon" => "",
                        "params" => "",
                        "is_show" => 10,
                        "children" => [],
                    ],
                    [
                        "title" => "角色管理-修改",
                        "path" => "admin/AdminRole/edit",
                        "component" => "form/index",
                        "method" => "GET",
                        "type" => "30",
                        "icon" => "",
                        "params" => "",
                        "is_show" => 10,
                        "children" => [],
                    ],
                    [
                        "title" => "角色管理-删除",
                        "path" => "admin/AdminRole/del",
                        "component" => "none/index",
                        "method" => "GET",
                        "type" => "30",
                        "icon" => "",
                        "params" => "",
                        "is_show" => 10,
                        "children" => [],
                    ],
                    [
                        "title" => "角色管理-授权",
                        "path" => "admin/AdminRole/auth",
                        "component" => "none/index",
                        "method" => "GET,PUT",
                        "type" => "30",
                        "icon" => "",
                        "params" => "",
                        "is_show" => 10,
                        "children" => [],
                    ],
                ],
            ],
            [
                "title" => "权限菜单",
                "path" => "admin/AdminRule/index",
                "component" => "table/index",
                "method" => "GET",
                "type" => "20",
                "icon" => "",
                "params" => "",
                "is_show" => 20,
                "children" => [
                    [
                        "title" => "权限菜单-表格",
                        "path" => "admin/AdminRule/index",
                        "component" => "none/index",
                        "method" => "GET",
                        "type" => "30",
                        "icon" => "",
                        "params" => "",
                        "is_show" => 10,
                        "children" => [],
                    ],
                    [
                        "title" => "权限菜单-添加",
                        "path" => "admin/AdminRule/add",
                        "component" => "form/index",
                        "method" => "GET",
                        "type" => "30",
                        "icon" => "",
                        "params" => "",
                        "is_show" => 10,
                        "children" => [],
                    ],
                    [
                        "title" => "权限菜单-修改",
                        "path" => "admin/AdminRule/edit",
                        "component" => "form/index",
                        "method" => "GET",
                        "type" => "30",
                        "icon" => "",
                        "params" => "",
                        "is_show" => 10,
                        "children" => [],
                    ],
                    [
                        "title" => "权限菜单-删除",
                        "path" => "admin/AdminRule/del",
                        "component" => "none/index",
                        "method" => "GET",
                        "type" => "30",
                        "icon" => "",
                        "params" => "",
                        "is_show" => 10,
                        "children" => [],
                    ],
                    [
                        "title" => "权限菜单-编辑列",
                        "path" => "admin/AdminRule/rowEdit",
                        "component" => "none/index",
                        "method" => "GET,PUT",
                        "type" => "30",
                        "icon" => "",
                        "params" => "",
                        "is_show" => 10,
                        "children" => [],
                    ],
                    [
                        "title" => "权限菜单-资源",
                        "path" => "admin/AdminRule/resources",
                        "component" => "form/index",
                        "method" => "GET,PUT",
                        "type" => "30",
                        "icon" => "",
                        "params" => "",
                        "is_show" => 10,
                        "children" => [],
                    ],
                ],
            ],
        ],
    ],
];